apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
spec:
  replicas: 1
  selector:
    matchLabels:
      role: p2
  template:
    metadata:
      labels:
        role: p2
    spec:
      containers:
      - name: p2
        image: alber2611/imagen2:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: p2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    role: p2

